/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo2;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author renat
 */
public class Tabuleiro extends javax.swing.JPanel {

    /**
     * Creates new form Tabuleiro
     */
    int j = 0;
    private Image Im_Tabuleiro;
    Peça pv = new Peça();
    Peça pp = new Peça();
    int[][]pos={{5,75,145,220,295,365,440,510,585,655},{650,650,650,650,650,650,650,650,650,650}};
    
    public void moverpv(){
        System.out.println(pos[1][1]);
        System.out.println(pos[2][1]);
       //for(int b = j;b<j+d;b++){
            //pv.setx(pos[1][b]);
            //pv.sety(pos[2][b]);
      // }
    }
    /*public void setpvx(int x){
        pv.setx(x);
    }
    
    public void setpvy(int y){
        pv.sety(y);
    }
    public void setppx(int x){
        pp.setx(x);
    }
    public void setppy(int y){
        pp.sety(y);
    }*/
    
    public Tabuleiro() {
        initComponents();
        ImageIcon icone = new ImageIcon("src\\imagens\\Tabuleiro.png");
        ImageIcon icone_v = new ImageIcon("src\\imagens\\Icone_Vermelho.png");
        ImageIcon icone_p = new ImageIcon("src\\imagens\\Icone_Preto.png");
        Image v = icone_v.getImage();
        Image p = icone_p.getImage();
        pv.setImage(v);
        pv.setx(5);
        pv.sety(650);
        pp.setImage(p);
        pp.setx(5);
        pp.sety(620);
        Im_Tabuleiro = icone.getImage();
        
    }
    public void paint(Graphics g){
        Graphics2D tela = (Graphics2D) g;
        tela.drawImage(Im_Tabuleiro,0,0,null);
        tela.drawImage(pv.get_image(),pv.getx(),pv.gety(),null);
        tela.drawImage(pp.get_image(),pp.getx(),pp.gety(),null);
        g.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(724, 693));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
 //1ª peça =